services:
  app:
    container_name: nextcloud
    image: nextcloud:31.0.8-apache
    restart: unless-stopped
    networks:
      - public
    volumes:
      - ./main:/var/www/html
      - ./data:/var/www/html/data
      - ./apps2:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./apache-conf-prefork.conf:/etc/apache2/conf-enabled/prefork.conf:ro
      - ./apache-modules-socache_shmcb.load:/etc/apache2/mods-enabled/socache_shmcb.load:ro
      - ./logs/nextcloud.log:/var/www/html/data/nextcloud.log

networks:
  public:
    external: true

